document.addEventListener('DOMContentLoaded', () => {
  const elements = [
  { symbol: 'H', position: { x: 2, y: 1 }, category: 'rød' },
  { symbol: 'He', position: { x: 19, y: 1 }, category: 'rød' },
  { symbol: 'Li', position: { x: 2, y: 2 }, category: 'rød' },
  { symbol: 'Be', position: { x: 3, y: 2 }, category: 'rød' },
  { symbol: 'B', position: { x: 14, y: 2 }, category: 'lilla' },
  { symbol: 'C', position: { x: 15, y: 2 }, category: 'lilla' },
  { symbol: 'N', position: { x: 16, y: 2 }, category: 'lilla' },
  { symbol: 'O', position: { x: 17, y: 2 }, category: 'lilla' },
  { symbol: 'F', position: { x: 18, y: 2 }, category: 'lilla' },
  { symbol: 'Ne', position: { x: 19, y: 2 }, category: 'lilla' },
  { symbol: 'Na', position: { x: 2, y: 3 }, category: 'rød' },
  { symbol: 'Mg', position: { x: 3, y: 3 }, category: 'rød' },
  { symbol: 'Al', position: { x: 14, y: 3 }, category: 'lilla' },
  { symbol: 'Si', position: { x: 15, y: 3 }, category: 'lilla' },
  { symbol: 'P', position: { x: 16, y: 3 }, category: 'lilla' },
  { symbol: 'S', position: { x: 17, y: 3 }, category: 'lilla' },
  { symbol: 'Cl', position: { x: 18, y: 3 }, category: 'lilla' },
  { symbol: 'Ar', position: { x: 19, y: 3 }, category: 'lilla' },
  { symbol: 'K', position: { x: 2, y: 4 }, category: 'rød' },
  { symbol: 'Ca', position: { x: 3, y: 4 }, category: 'rød' },
  { symbol: 'Sc', position: { x: 4, y: 4 }, category: 'blå' },
  { symbol: 'Ti', position: { x: 5, y: 4 }, category: 'blå' },
  { symbol: 'V', position: { x: 6, y: 4 }, category: 'blå' },
  { symbol: 'Cr', position: { x: 7, y: 4 }, category: 'blå' },
  { symbol: 'Mn', position: { x: 8, y: 4 }, category: 'blå' },
  { symbol: 'Fe', position: { x: 9, y: 4 }, category: 'blå' },
  { symbol: 'Co', position: { x: 10, y: 4 }, category: 'blå' },
  { symbol: 'Ni', position: { x: 11, y: 4 }, category: 'blå' },
  { symbol: 'Cu', position: { x: 12, y: 4 }, category: 'blå' },
  { symbol: 'Zn', position: { x: 13, y: 4 }, category: 'blå' },
  { symbol: 'Ga', position: { x: 14, y: 4 }, category: 'lilla' },
  { symbol: 'Ge', position: { x: 15, y: 4 }, category: 'lilla' },
  { symbol: 'As', position: { x: 16, y: 4 }, category: 'lilla' },
  { symbol: 'Se', position: { x: 17, y: 4 }, category: 'lilla' },
  { symbol: 'Br', position: { x: 18, y: 4 }, category: 'lilla' },
  { symbol: 'Kr', position: { x: 19, y: 4 }, category: 'lilla' },
  { symbol: 'Rb', position: { x: 2, y: 5 }, category: 'rød' },
  { symbol: 'Sr', position: { x: 3, y: 5 }, category: 'rød' },
  { symbol: 'Y', position: { x: 4, y: 5 }, category: 'blå' },
  { symbol: 'Zr', position: { x: 5, y: 5 }, category: 'blå' },
  { symbol: 'Nb', position: { x: 6, y: 5 }, category: 'blå' },
  { symbol: 'Mo', position: { x: 7, y: 5 }, category: 'blå' },
  { symbol: 'Tc', position: { x: 8, y: 5 }, category: 'blå' },
  { symbol: 'Ru', position: { x: 9, y: 5 }, category: 'blå' },
  { symbol: 'Rh', position: { x: 10, y: 5 }, category: 'blå' },
  { symbol: 'Pd', position: { x: 11, y: 5 }, category: 'blå' },
  { symbol: 'Ag', position: { x: 12, y: 5 }, category: 'blå' },
  { symbol: 'Cd', position: { x: 13, y: 5 }, category: 'blå' },
  { symbol: 'In', position: { x: 14, y: 5 }, category: 'lilla' },
  { symbol: 'Sn', position: { x: 15, y: 5 }, category: 'lilla' },
  { symbol: 'Sb', position: { x: 16, y: 5 }, category: 'lilla' },
  { symbol: 'Te', position: { x: 17, y: 5 }, category: 'lilla' },
  { symbol: 'I', position: { x: 18, y: 5 }, category: 'lilla' },
  { symbol: 'Xe', position: { x: 19, y: 5 }, category: 'lilla' },
  { symbol: 'Cs', position: { x: 2, y: 6 }, category: 'rød' },
  { symbol: 'Fr', position: { x: 2, y: 7 }, category: 'rød' },
  { symbol: 'Ba', position: { x: 3, y: 6 }, category: 'rød' },
  { symbol: 'Ra', position: { x: 3, y: 7 }, category: 'rød' },
  { symbol: 'Lu', position: { x: 4, y: 6 }, category: 'blå' },
  { symbol: 'Lr', position: { x: 4, y: 7 }, category: 'blå' },  
  { symbol: 'Ce', position: { x: 5, y: 9 }, category: 'grøn' },
  { symbol: 'La', position: { x: 4, y: 9 }, category: 'grøn' },
  { symbol: 'Ac', position: { x: 4, y: 10 }, category: 'grøn' },
  { symbol: 'Th', position: { x: 5, y: 10 }, category: 'grøn' },
  { symbol: 'Pa', position: { x: 6, y: 10 }, category: 'grøn' },
  { symbol: 'U', position: { x: 7, y: 10 }, category: 'grøn' },
  { symbol: 'Np', position: { x: 8, y: 10 }, category: 'grøn' },
  { symbol: 'Pu', position: { x: 9, y: 10 }, category: 'grøn' },
  { symbol: 'Am', position: { x: 10, y: 10 }, category: 'grøn' },
  { symbol: 'Cm', position: { x: 11, y: 10 }, category: 'grøn' },
  { symbol: 'Bk', position: { x: 12, y: 10 }, category: 'grøn' },
  { symbol: 'Cf', position: { x: 13, y: 10 }, category: 'grøn' },
  { symbol: 'Es', position: { x: 14, y: 10 }, category: 'grøn' },
  { symbol: 'Fm', position: { x: 15, y: 10 }, category: 'grøn' },
  { symbol: 'Md', position: { x: 16, y: 10 }, category: 'grøn' },
  { symbol: 'No', position: { x: 17, y: 10 }, category: 'grøn' },
  { symbol: 'Pr', position: { x: 6, y: 9 }, category: 'grøn' },
  { symbol: 'Nd', position: { x: 7, y: 9 }, category: 'grøn' },
  { symbol: 'Pm', position: { x: 8, y: 9 }, category: 'grøn' },
  { symbol: 'Sm', position: { x: 9, y: 9 }, category: 'grøn' },
  { symbol: 'Eu', position: { x: 10, y: 9 }, category: 'grøn' },
  { symbol: 'Gd', position: { x: 11, y: 9 }, category: 'grøn' },
  { symbol: 'Tb', position: { x: 12, y: 9 }, category: 'grøn' },
  { symbol: 'Dy', position: { x: 13, y: 9 }, category: 'grøn' },
  { symbol: 'Ho', position: { x: 14, y: 9 }, category: 'grøn' },
  { symbol: 'Er', position: { x: 15, y: 9 }, category: 'grøn' },
  { symbol: 'Tm', position: { x: 16, y: 9 }, category: 'grøn' },
  { symbol: 'Yb', position: { x: 17, y: 9 }, category: 'grøn' },
  { symbol: 'Hf', position: { x: 5, y: 6 }, category: 'blå' },
  { symbol: 'Ta', position: { x: 6, y: 6 }, category: 'blå' },
  { symbol: 'W', position: { x: 7, y: 6 }, category: 'blå' },
  { symbol: 'Re', position: { x: 8, y: 6 }, category: 'blå' },
  { symbol: 'Os', position: { x: 9, y: 6 }, category: 'blå' },
  { symbol: 'Ir', position: { x: 10, y: 6 }, category: 'blå' },
  { symbol: 'Pt', position: { x: 11, y: 6 }, category: 'blå' },
  { symbol: 'Au', position: { x: 12, y: 6 }, category: 'blå' },
  { symbol: 'Hg', position: { x: 13, y: 6 }, category: 'blå' },
  { symbol: 'Tl', position: { x: 14, y: 6 }, category: 'lilla' },
  { symbol: 'Pb', position: { x: 15, y: 6 }, category: 'lilla' },
  { symbol: 'Bi', position: { x: 16, y: 6 }, category: 'lilla' },
  { symbol: 'Po', position: { x: 17, y: 6 }, category: 'lilla' },
  { symbol: 'At', position: { x: 18, y: 6 }, category: 'lilla' },
  { symbol: 'Rn', position: { x: 19, y: 6 }, category: 'lilla' },
  { symbol: 'Rf', position: { x: 5, y: 7 }, category: 'blå' },
  { symbol: 'Db', position: { x: 6, y: 7 }, category: 'blå' },
  { symbol: 'Sg', position: { x: 7, y: 7 }, category: 'blå' },
  { symbol: 'Bh', position: { x: 8, y: 7 }, category: 'blå' },
  { symbol: 'Hs', position: { x: 9, y: 7 }, category: 'blå' },
  { symbol: 'Mt', position: { x: 10, y: 7 }, category: 'blå' },
  { symbol: 'Ds', position: { x: 11, y: 7 }, category: 'blå' },
  { symbol: 'Rg', position: { x: 12, y: 7 }, category: 'blå' },
  { symbol: 'Cn', position: { x: 13, y: 7 }, category: 'blå' },
  { symbol: 'Nh', position: { x: 14, y: 7 }, category: 'lilla' },
  { symbol: 'Fl', position: { x: 15, y: 7 }, category: 'lilla' },
  { symbol: 'Mc', position: { x: 16, y: 7 }, category: 'lilla' },
  { symbol: 'Lv', position: { x: 17, y: 7 }, category: 'lilla' },
  { symbol: 'Ts', position: { x: 18, y: 7 }, category: 'lilla' },
  { symbol: 'Og', position: { x: 19, y: 7 }, category: 'lilla' },
  ];

  const periodicTable = document.querySelector('.periodic-table')

  elements.forEach((element) => {
      const button = document.createElement('button');
      button.classList.add('element', element.category);  // Add category class
      button.textContent = element.symbol;
      button.style.gridColumn = element.position.x;
      button.style.gridRow = element.position.y;
      periodicTable.appendChild(button);
      button.addEventListener("click", () =>{location.href='https://da.wikipedia.org/wiki/Erbium';} );
    }); 
});