document.addEventListener('DOMContentLoaded', () => {
  const elements = [
  { symbol: 'H', position: { x: 2, y: 1 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Brint'},
  { symbol: 'He', position: { x: 19, y: 1 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Helium' },
  { symbol: 'Li', position: { x: 2, y: 2 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Lithium' },
  { symbol: 'Be', position: { x: 3, y: 2 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Beryllium' },
  { symbol: 'B', position: { x: 14, y: 2 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Bor_(grundstof)' },
  { symbol: 'C', position: { x: 15, y: 2 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Carbon' },
  { symbol: 'N', position: { x: 16, y: 2 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Kv%C3%A6lstof' },
  { symbol: 'O', position: { x: 17, y: 2 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Ilt' },
  { symbol: 'F', position: { x: 18, y: 2 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Fluor' },
  { symbol: 'Ne', position: { x: 19, y: 2 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Neon' },
  { symbol: 'Na', position: { x: 2, y: 3 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Natrium' },
  { symbol: 'Mg', position: { x: 3, y: 3 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Magnesium' },
  { symbol: 'Al', position: { x: 14, y: 3 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Aluminium' },
  { symbol: 'Si', position: { x: 15, y: 3 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Silicium' },
  { symbol: 'P', position: { x: 16, y: 3 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Fosfor' },
  { symbol: 'S', position: { x: 17, y: 3 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Svovl' },
  { symbol: 'Cl', position: { x: 18, y: 3 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Klor' },
  { symbol: 'Ar', position: { x: 19, y: 3 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Argon' },
  { symbol: 'K', position: { x: 2, y: 4 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Kalium' },
  { symbol: 'Ca', position: { x: 3, y: 4 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Kalk' },
  { symbol: 'Sc', position: { x: 4, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Scandium' },
  { symbol: 'Ti', position: { x: 5, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Titan_(grundstof)' },
  { symbol: 'V', position: { x: 6, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Vanadium' },
  { symbol: 'Cr', position: { x: 7, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Krom' },
  { symbol: 'Mn', position: { x: 8, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Mangan' },
  { symbol: 'Fe', position: { x: 9, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Jern' },
  { symbol: 'Co', position: { x: 10, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Kobolt' },
  { symbol: 'Ni', position: { x: 11, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Nikkel' },
  { symbol: 'Cu', position: { x: 12, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Kobber' },
  { symbol: 'Zn', position: { x: 13, y: 4 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Zink' },
  { symbol: 'Ga', position: { x: 14, y: 4 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Gallium' },
  { symbol: 'Ge', position: { x: 15, y: 4 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Germanium' },
  { symbol: 'As', position: { x: 16, y: 4 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Arsen' },
  { symbol: 'Se', position: { x: 17, y: 4 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Selen' },
  { symbol: 'Br', position: { x: 18, y: 4 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Brom' },
  { symbol: 'Kr', position: { x: 19, y: 4 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Krypton' },
  { symbol: 'Rb', position: { x: 2, y: 5 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Rubidium' },
  { symbol: 'Sr', position: { x: 3, y: 5 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Strontium' },
  { symbol: 'Y', position: { x: 4, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Yttrium' },
  { symbol: 'Zr', position: { x: 5, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Zirconium' },
  { symbol: 'Nb', position: { x: 6, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Niobium' },
  { symbol: 'Mo', position: { x: 7, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Molybd%C3%A6n' },
  { symbol: 'Tc', position: { x: 8, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Technetium' },
  { symbol: 'Ru', position: { x: 9, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Ruthenium' },
  { symbol: 'Rh', position: { x: 10, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Rhodium' },
  { symbol: 'Pd', position: { x: 11, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Palladium' },
  { symbol: 'Ag', position: { x: 12, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/S%C3%B8lv' },
  { symbol: 'Cd', position: { x: 13, y: 5 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Cadmium' },
  { symbol: 'In', position: { x: 14, y: 5 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Indium' },
  { symbol: 'Sn', position: { x: 15, y: 5 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Tin' },
  { symbol: 'Sb', position: { x: 16, y: 5 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Antimon' },
  { symbol: 'Te', position: { x: 17, y: 5 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Tellur' },
  { symbol: 'I', position: { x: 18, y: 5 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Jod' },
  { symbol: 'Xe', position: { x: 19, y: 5 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Xenon' },
  { symbol: 'Cs', position: { x: 2, y: 6 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/C%C3%A6sium' },
  { symbol: 'Fr', position: { x: 2, y: 7 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Francium' },
  { symbol: 'Ba', position: { x: 3, y: 6 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Barium' },
  { symbol: 'Ra', position: { x: 3, y: 7 }, category: 'rød', url: 'https://da.wikipedia.org/wiki/Radium' },
  { symbol: 'Lu', position: { x: 4, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Lutetium' },
  { symbol: 'Lr', position: { x: 4, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Lawrencium' },  
  { symbol: 'Ce', position: { x: 5, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Cerium' },
  { symbol: 'La', position: { x: 4, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Lanthan' },
  { symbol: 'Ac', position: { x: 4, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Actinium' },
  { symbol: 'Th', position: { x: 5, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Thorium' },
  { symbol: 'Pa', position: { x: 6, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Protactinium' },
  { symbol: 'U', position: { x: 7, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Uran' },
  { symbol: 'Np', position: { x: 8, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Neptunium' },
  { symbol: 'Pu', position: { x: 9, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Plutonium' },
  { symbol: 'Am', position: { x: 10, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Americium' },
  { symbol: 'Cm', position: { x: 11, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Curium' },
  { symbol: 'Bk', position: { x: 12, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Berkelium' },
  { symbol: 'Cf', position: { x: 13, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Californium' },
  { symbol: 'Es', position: { x: 14, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Einsteinium' },
  { symbol: 'Fm', position: { x: 15, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Fermium' },
  { symbol: 'Md', position: { x: 16, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Mendelevium' },
  { symbol: 'No', position: { x: 17, y: 10 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Nobelium' },
  { symbol: 'Pr', position: { x: 6, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Praseodym' },
  { symbol: 'Nd', position: { x: 7, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Neodym' },
  { symbol: 'Pm', position: { x: 8, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Promethium' },
  { symbol: 'Sm', position: { x: 9, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Samarium' },
  { symbol: 'Eu', position: { x: 10, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Europium' },
  { symbol: 'Gd', position: { x: 11, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Gadolinium' },
  { symbol: 'Tb', position: { x: 12, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Terbium' },
  { symbol: 'Dy', position: { x: 13, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Dysprosium' },
  { symbol: 'Ho', position: { x: 14, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Holmium' },
  { symbol: 'Er', position: { x: 15, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Erbium' },
  { symbol: 'Tm', position: { x: 16, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Thulium' },
  { symbol: 'Yb', position: { x: 17, y: 9 }, category: 'grøn', url: 'https://da.wikipedia.org/wiki/Ytterbium' },
  { symbol: 'Hf', position: { x: 5, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Hafnium' },
  { symbol: 'Ta', position: { x: 6, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Tantal' },
  { symbol: 'W', position: { x: 7, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Wolfram' },
  { symbol: 'Re', position: { x: 8, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Rhenium' },
  { symbol: 'Os', position: { x: 9, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Osmium' },
  { symbol: 'Ir', position: { x: 10, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Iridium' },
  { symbol: 'Pt', position: { x: 11, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Platin' },
  { symbol: 'Au', position: { x: 12, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Guld' },
  { symbol: 'Hg', position: { x: 13, y: 6 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Kviks%C3%B8lv' },
  { symbol: 'Tl', position: { x: 14, y: 6 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Thallium' },
  { symbol: 'Pb', position: { x: 15, y: 6 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Bly' },
  { symbol: 'Bi', position: { x: 16, y: 6 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Bismuth' },
  { symbol: 'Po', position: { x: 17, y: 6 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Polonium' },
  { symbol: 'At', position: { x: 18, y: 6 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Astat' },
  { symbol: 'Rn', position: { x: 19, y: 6 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Radon' },
  { symbol: 'Rf', position: { x: 5, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Rutherfordium' },
  { symbol: 'Db', position: { x: 6, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Dubnium' },
  { symbol: 'Sg', position: { x: 7, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Seaborgium' },
  { symbol: 'Bh', position: { x: 8, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Bohrium' },
  { symbol: 'Hs', position: { x: 9, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Hassium' },
  { symbol: 'Mt', position: { x: 10, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Meitnerium' },
  { symbol: 'Ds', position: { x: 11, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Darmstadtium' },
  { symbol: 'Rg', position: { x: 12, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/R%C3%B8ntgenium' },
  { symbol: 'Cn', position: { x: 13, y: 7 }, category: 'blå', url: 'https://da.wikipedia.org/wiki/Copernicium' },
  { symbol: 'Nh', position: { x: 14, y: 7 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Nihonium' },
  { symbol: 'Fl', position: { x: 15, y: 7 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Flerovium' },
  { symbol: 'Mc', position: { x: 16, y: 7 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Moscovium' },
  { symbol: 'Lv', position: { x: 17, y: 7 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Livermorium' },
  { symbol: 'Ts', position: { x: 18, y: 7 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Tennessin' },
  { symbol: 'Og', position: { x: 19, y: 7 }, category: 'lilla', url: 'https://da.wikipedia.org/wiki/Oganesson' },
  ];

  const periodicTable = document.querySelector('.periodic-table')
  

  elements.forEach((element) => {
    const button = document.createElement('button');
    button.classList.add('element', element.category);
    button.textContent = element.symbol;
    button.style.gridColumn = element.position.x;
    button.style.gridRow = element.position.y;

    periodicTable.appendChild(button);
    button.addEventListener('click', (e) => {
      e.preventDefault();
      window.open(element.url, '_blank');
    });
  });  
});

